### ISSUE TITLE
How to update to typst 0.12.0?

### ISSUE THREAD

**Issue by crd2333** [OverflowCat/astro-typst#1]
I'm not familiar with astro's packages and their dependencies. It seems although I have changed the version of typst-node-compiler, the pages are still rendered in 0.11.1.
I wonder if this can be solved by the update of astro-typst. Also, I'm looking forward to ”Responsive SVGs“ feature and there have been long time since last update (

**Comment by OverflowCat** [comment]
Some files encounter errors during rendering on my end after bumping
typst.ts to 0.5.0-rc8, and I’m not sure why. If you want to test it
for yourself, you could try upgrading the package.json in this
project. The documentation on responsive SVGs by the author is still
incomplete. I don’t have time to debug or develop further at the
moment; happy hacking XD

**Comment by OverflowCat** [comment]
***@***.*** has been published and works well for me. You
might want to give it a try. Remember to update to
***@***.***/typst-ts-node-compiler": "0.5.0-rc9".

(Turns out that the errors were from rehype-typst, which hasn't
published a new version on npm yet, rather than my astro-typst 😅)
